# This is a basic workflow to help you get started with Actions

name: ${{ github.actor }} is testing out
env:
  GITHUB_ACTIONS: "Blabla"


on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-task-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checking env variable
      run: echo "GITHUB_ACTIONS env variable equals to ${{ env.GITHUB_ACTIONS }}"
    - name: Checking branch name
      run: echo "Name of your branch is ${{ github.ref }} and repo is ${{ github.repository }}"
    - name: Checing env variable
      run: echo "The job event: ${{ github.event_name }}"
    
